name = mcl_lun_items
description = Lunatic items (Gohei)
depends = mcl_core, mcl_bows, mcl_lun_homing, mcl_lun_sounds
depends = mcl_core, mcl_bows, mcl_lun_homing, mcl_lun_sounds, colors_api
optional_depends = wielded_light, mcl_potions
